### PR TITLE
Set UserAgent to Facebook's scraper

### PR DESCRIPTION
**Pull request by mattgrayisok**
Required to get decent meta data from a few sites including amazon.co.uk

### CODE REVIEW

**Comment by tomaj** [comment]
Thank you for pull request. This feature looks good bud I will recommend to use protected field `$userAgent` for this. You can add `__constructor` to set this user-agent externally when creating. Can you change it?

**Comment by lmfmaier** [comment]
I have added a pr with constructor options for the Scraper

https://github.com/tomaj/meta-scraper/pull/4

**Comment by tomaj** [comment]
i was thinking about something like this:

```
public function __constructor(...,$clientParams = [])
{
  $this->clientParams = $clientParams;
 // ...
}
....
public function parseUrl($url, $timeout = 5)	
{	   
        $client = new Client($this->clientParams);
```

this will be more generic solution, you can pass any guzzle client params via constructor - for example facebook user agent

**Comment by tomaj** [comment]
looks like it is solved via #4

**Comment by tomaj** [comment]
Fixed byt #4 - you can pass user agent with constructor

**Pull request closed without merging**
